language: python

git:
  submodules: false
  
os:
  - linux

python:
  - 3.5
  - 3.6

install:
  - sudo apt-get update
  - wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh;
  - bash miniconda.sh -b -p $HOME/miniconda
  - export PATH="$HOME/miniconda/bin:$PATH"
  - hash -r
  - conda config --set always_yes yes --set changeps1 no
  - conda update -q conda
  # Useful for debugging any issues with conda
  - conda info -a
  - conda create -q -n test-environment python=$TRAVIS_PYTHON_VERSION
  - source activate test-environment
  - conda install pytorch-cpu torchvision-cpu -c pytorch
  - conda install pytest
  - conda install pytest-cov
  - conda install -c conda-forge codecov
  - pip install pytz
  - pip install codeclimate-test-reporter
  - python setup.py install

script:
  - python setup.py test #codeclimate-test-reporter --token f73b27a29cb0c7bd5da5ce476412743bfc6d31a094f1806434332c2e5c92381f
  - codecov
  
before_deploy:
- pip install twine

deploy:
  provider: pypi
  user: 0h-n0
  password:
    secure: ZmO7h0ZsMaKnqd9fYpxaNi7TvHbx3kh22C3nSbXupBksaeHAaGqVGXsgHMVXndE1l5n576LqcR8kZOXqVMhejw2VlPvsHHbcKGt4437n98c2T8XbkcP7DXDI3KmLKxdA0ez73C5igfJnpli7uFd5kg4ci0BQT8Y55HURbDxni2/m2lQLuiUiZ9fI+H8vszmKDBJlP6xHSEmGsgGo/2QSeM3aRN+VvxuoDazHrYxauUCGobuk2RryPT3fk6aHEc+iojEA1/lAC5JAbp74ciYGjcPr+p/B7VuRNqidlUV87Y/RSSlrIXPMz7krbB2RCNdblOCPPeqljrItLVRouMikW1U6K/+6sJTJwCXqqrLHR6RkBoO28gj4l8Y0Sou+GMa5mK9EyBbPvtbUgg1pGYyEsWy4cElN5viHo+x2lidrqsbdvtVLDwzmBA7gbVuSW6V4YOBvzgKklH81cP1Ov/67XjX307Bi9AAe9Ke+FC1bVIc7DqHD13Fl4BWCiNGgWoBl/w53lZtY2Gt0soiCtSrkvwylrF6oynYPbEILNCF5BrGEAFY8mRQbjN0Ye/67gP8baHMCDUjxHjadCyF5w59Sa+sTqGaCho6bgpF5DBoebEg7TlabFSLsCZ3eUSW/QEvFJ732BNgkIlI7WkFYDZwjIidZ95ZnsNHnWSRn1n3z1FU=
  on:
    repo: 0h-n0/torchex
    python: 3.6
    branch: master
    tags: true
    
  distributions: dists
  skip_cleanup: true
  skip_upload_docs: true            
